### ISSUE TITLE
[BUG] Unable to pull data for a longer date range

### ISSUE THREAD

**Issue by benjcabalona1029** [enzoampil/fastquant#106]
Tried downloading 2010 - 2020 data for JFC using the code below.

```python
from fastquant import get_stock_data
data = get_stock_data("JFC", "2010-01-01", "2020-01-01")
```

Error Message:

```python
9it [00:08,  1.06s/it]

Symbol {} not found in phisix after the first {} date iterations!


[*********************100%***********************]  1 of 1 completed



```

**Comment by jgendrinal** [comment]
Will try the same implementation in R. Have a feeling phsix only supports a very limited date range.

**Comment by jgendrinal** [comment]
Is this issue still persisting?

**Comment by enzoampil** [comment]
@jgendrinal Yeah, no fix yet. Feel free to take it on if bandwidth allows :smile: I can take on some of these pending bugs potentially next week.

**Comment by Leez94** [comment]
Hi!
I tried downloading 2010-2020 JFC data and it works fine.

```
from fastquant import get_stock_data
df = get_stock_data("JFC", "2010-01-01", "2020-07-30")
print (df)
```
Output

```
         close
dt               
2010-01-04   55.5
2010-01-05   59.0
2010-01-06   59.0
2010-01-07   59.0
2010-01-08   59.0
...           ...
2020-07-24  128.5
2020-07-27  128.0
2020-07-28  129.1
2020-07-29  131.0
2020-07-30  135.0

[2462 rows x 1 columns]
```

but when i use this code below, an error occurs.
```
from fastquant import get_stock_data
df = get_stock_data("JFC", "2010-01-01", "2020-07-30", source="phisix", format="cv")
print (df)
```

error message:
```
JFC not found in phisix after the first 10 date iterations!
AttributeError: 'NoneType' object has no attribute 'dt'
```

**Comment by enzoampil** [comment]
Thanks @Leez94 , yes, please just use the first snippet version for now while we sort out this issue :smile:

**Comment by enzoampil** [comment]
@benjamincabalona1029 I actually realized that this issue of having the first year at 2010 is based on the file we use to cache our results (only backfilled to prior to 2010). To address this, we'll have to make pulls with start dates prior to 2010 work beyond the caching supported.

**Comment by jpdeleon** [comment]
@enzoampil I didn't notice that the starting date requested above is 2010. I used "2010-01-01" as the default earliest date in data cache. May be we should archive all the way 2000 and this does not include volume data. We really have to query phisix for volume separately and add it to data cache.

**Comment by enzoampil** [comment]
@jpdeleon yes, we can do that. Only hesitation from me is if the cache file gets too big; otherwise, should be fine :smile:

**Comment by skyphyr** [comment]
I just implemented a fix for this in crypto, should be easy to port across to stock data
https://github.com/enzoampil/fastquant/pull/368/commits

**Comment by jpdeleon** [comment]
The original issue posted by @benjcabalona1029 and a separate issue by @Leez94 have been fixed. Please re-open if related issues persist.
